Arithmetic
Krasns/csharp-basics-exercises pull request #3
Opened 2021-07-21 18:58 UTC by Krasns

2021-07-22 18:31 UTC, ausmoons requested changes

2021-07-22 18:31 UTC, ausmoons commented on Arithmetic/CalculateArea/Geometry.cs
> +            throw new NotImplementedException();
Sis ir izpildits?

2021-07-22 18:31 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +                else if (choice == 1)
Tev pat nav jaunakais codelex repo

2021-07-22 18:31 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +        public static void calculateRectangleArea()
ar lielo burtu metode

2021-07-22 18:31 UTC, ausmoons commented on Arithmetic/Exercise1/Program.cs
> +            if (FirstNumber == 15 || SecondNumber == 15)
Šos visus zem viena if, jo atgriez vienu un to pasu

2021-07-22 18:31 UTC, ausmoons commented on Arithmetic/Exercise8/Program.cs
> +            double Pay = 0;
Sie ar mazo burtu

2021-07-22 18:31 UTC, ausmoons commented on Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"your BMI is {BMI} ,eat less!!");
18.5 bus seit. Vai tas ir pareizi?

2021-07-23 16:45 UTC, Krasns commented on Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"your BMI is {BMI} ,eat less!!");
tur parādīs visus BMI, kas ir virs 25, tāpēc ir ēst vairāk.

2021-07-24 08:51 UTC, ausmoons commented on Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"your BMI is {BMI} ,eat less!!");
Un kur būs 18.5?

2021-07-26 15:18 UTC, Krasns commented on Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"your BMI is {BMI} ,eat less!!");
pirmajā if samainiju no (BMI < 18.5) uz (BMI <= 18.5), lai 18.5 būtu ieskaitīts.

2021-07-26 18:16 UTC, Krasns commented on Arithmetic/CalculateArea/Geometry.cs
> +            throw new NotImplementedException();
izmainītos darbus, kas lejā parādās, viņus var uzreiz redzēt?

2021-07-26 18:17 UTC, Krasns commented on Arithmetic/CalculateArea/Program.cs
> +                else if (choice == 1)
izmainiju, nebiju izlasijis kārtīgi.

2021-07-27 16:34 UTC, ausmoons requested changes

2021-07-27 16:34 UTC, ausmoons commented on Arithmetic/CalculateArea/Geometry.cs
> +            throw new NotImplementedException();
Izmaiņas parāās, bet tu izlasīji, kas ir šis  throw new NotImplementedException();? -- tas ir jādzēš ārā. Un visus PR komentārus var labot vienā commitā

2021-07-28 18:14 UTC, ausmoons approved these changes

2021-07-29 16:04 UTC, closed without merging

2021-07-29 17:32 UTC, ausmoons commented on Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"your BMI is {BMI} ,eat less!!");
Kas notike ar šo PR?