Arrays
Krasns/csharp-basics-exercises pull request #6
Opened 2021-08-11 14:36 UTC by Krasns

2021-08-12 15:32 UTC, ausmoons requested changes

2021-08-12 15:32 UTC, ausmoons commented on .gitignore
> +**/**/AssemblyInfo.cs
Kāpēc tu domā, ka šis ir jāliek gitignore? Un kāpēc tu vispār tagad aiztiec gitignore un pie tam vēl ne main

2021-08-12 15:32 UTC, ausmoons commented on Arrays/Exercise4/Program.cs
> +                    Console.ReadKey();
Te nav pareizi tab

2021-08-12 15:32 UTC, ausmoons commented on Arrays/Exercise8/Program.cs
> +                } while (wrong != word.Length + 10 && right != word.Length);
Kas tas pa + 10?

2021-08-12 15:32 UTC, ausmoons commented on Arrays/TicTacToe/Program.cs
> +                                count = 8;
Tas kas ir iekšā, atkārtojas. Tas nav labi. Izdomā ko pamainīt, lai nebūtu lieki jāatkārto kods

2021-08-12 15:32 UTC, ausmoons commented on Arrays/TicTacToe/Program.cs.orig
> +<<<<<<< HEAD
Un te vispār ir merge confliktu un šis fails ir lieks. Ja būtu skatījies, ko com mito, būtu pats pamanījis

2021-08-12 17:54 UTC, Krasns commented on Arrays/Exercise8/Program.cs
> +                } while (wrong != word.Length + 10 && right != word.Length);
vārda garums + 10 reizes varēs meiģināt uzminēt pareizos burtus.

2021-08-12 17:57 UTC, Krasns commented on Arrays/TicTacToe/Program.cs.orig
> +<<<<<<< HEAD
man viņi parādijās un viņus izdzēsu āra.

2021-08-12 19:50 UTC, ausmoons commented on Arrays/TicTacToe/Program.cs.orig
> +<<<<<<< HEAD
Program.cs.orig  -- tev šis fails nebija jāpusho

2021-08-12 19:51 UTC, ausmoons commented on .gitignore
> +**/**/AssemblyInfo.cs
Pamēģināji pats noklonēt branchu un palaist programmas?

2021-09-07 18:18 UTC, ausmoons approved these changes

2021-09-25 17:16 UTC, merged